<?php

namespace Database\Seeders;

use App\Models\Bidang;
use App\Models\Unit;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
  public function run(): void
  {
    // ------------------------------ SEEDING NON UNIT USER ------------------------------ //

    User::factory()->create([
      'id' => '9d41cd56-e46d-48d1-8739-305b32bfab33',
      'name' => 'Administrator',
      'email' => 'admin@admin.com',
      'password' => '$2y$12$y.5MaysrjgvzzBSWAafL1OCURe3JQqpx4Lc/lxnpUALYBqvHkQ3kq',
      'role_id' => 2,
    ])->assignRole('administrator');

    User::factory()->create([
      'id' => '9d41cd57-4f32-4bbc-97c1-943797086814',
      'name' => 'Pimpinan',
      'email' => 'pimpinan@admin.com',
      'password' => '$2y$12$y.5MaysrjgvzzBSWAafL1OCURe3JQqpx4Lc/lxnpUALYBqvHkQ3kq',
      'role_id' => 3,
    ])->assignRole('pimpinan');

    User::factory()->create([
      'id' => '9d41cd57-4f3c-4685-9344-ca46ac380db6',
      'name' => 'Perencana',
      'email' => 'perencana@admin.com',
      'password' => '$2y$12$y.5MaysrjgvzzBSWAafL1OCURe3JQqpx4Lc/lxnpUALYBqvHkQ3kq',
      'role_id' => 4,
    ])->assignRole('perencana');

    // ------------------------------ SEEDING BIDANG USER ------------------------------ //

    Bidang::all()->each(function ($bidang) {
      User::factory()->create([
        'id' => Str::orderedUuid(),
        'name' => $bidang->b_name,
        'email' => Str::slug($bidang->b_name, '') . '@admin.com',
        "password" => '$2y$12$y.5MaysrjgvzzBSWAafL1OCURe3JQqpx4Lc/lxnpUALYBqvHkQ3kq',
        'role_id' => 6,
        'bidang_id' => $bidang->id,
      ])->assignRole('bidang');
    });

    // ------------------------------ SEEDING UNIT USER ------------------------------ //

    // Unit::all()->each(function ($unit) {
    //   User::factory()->create([
    //     'id' => Str::orderedUuid(),
    //     'name' => $unit->u_name,
    //     'email' => 'unit' . fake()->unique()->numberBetween($min = 1000, $max = 9000) . '@admin.com',
    //     "password" => "$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq",
    //     'role_id' => 5,
    //     'unit_id' => $unit->id,
    //   ]);
    // });

    // Seeds below are generated by code above //

    $user_unit = [
      [
        "id" => "9d41ceac-a6dd-48fe-b6a1-f1507d871ddb",
        "name" => "Kelompok Staf Medis",
        "email" => "unit2213@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d1fe-530c-470b-b815-a85a0e9b9ae0",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41ceac-a777-4295-a569-dde44b82d869",
        "name" => "Sub Bidang Pelayanan Medis",
        "email" => "unit8690@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d3ba-68fb-4013-8899-ad5aeb0b7fd4",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41ceac-a77a-4644-964a-8b41484c03dd",
        "name" => "Instalasi Rawat Inap",
        "email" => "unit6913@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d3ba-69f3-4ce5-b26e-0eb0bcb935ca",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41cf63-edfe-40b6-97c8-b30c5bc32ae7",
        "name" => "Instalasi Rawat Jalan",
        "email" => "unit7182@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d3ba-69fa-4d49-b306-ffd0a0621117",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41cf63-ee9a-40a9-a4eb-f9b0f8a2ee4f",
        "name" => "Instalasi Kamar Bersalin",
        "email" => "unit8171@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d3ba-69fd-415d-8b7d-891fdf270685",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41cf63-ee9e-49c4-9be0-2f18d9f184e6",
        "name" => "Instalasi Bedah Sentral",
        "email" => "unit2623@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d3ba-69ff-49d1-bd09-d08037bda712",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41cfbb-b307-4a54-8ec1-3ac376b24fc1",
        "name" => "ICCU",
        "email" => "unit7393@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d3ba-6a04-4578-bac4-068900a71409",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41cfbb-b3a0-4b7a-b8a6-45e957fbdf88",
        "name" => "ICU",
        "email" => "unit1986@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d3ba-6a06-4615-9d10-67d436fe774a",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41cfbb-b3a3-41d9-9ed4-9abc0c4c1f2b",
        "name" => "NICU",
        "email" => "unit8834@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d3ba-6a0a-49fa-b269-7c0d8c16faad",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41d024-6d5f-4cb7-8428-50c15e296a48",
        "name" => "PICU",
        "email" => "unit3858@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d3ba-6a0c-464a-96bd-adf529aad930",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41d024-6de2-4f9e-918e-d59d4c822db6",
        "name" => "Sub Bidang Pelayanan Keperawatan",
        "email" => "unit3079@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d3ba-6a0d-4d62-a6f4-ff846c4fea41",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41d024-6de5-4c4f-9a3a-d45c1fa2190b",
        "name" => "Instalasi Radiologi",
        "email" => "unit3865@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d48d-2a81-4887-be1d-6c563519fc33",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41d06a-241a-4413-a46f-c856e57fbfb6",
        "name" => "Instalasi Gizi",
        "email" => "unit4117@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d48d-2aff-4782-988a-35c9b59dfff7",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41d06a-2497-4878-b74d-afa77c9cdfec",
        "name" => "Instalasi Patologi Klinik",
        "email" => "unit8516@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d48d-2b02-4ce0-b7c6-69799853f438",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41d06a-249b-4d80-93d9-56f9ce080e0f",
        "name" => "Instalasi Rehabilitasi Medik",
        "email" => "unit7925@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d48d-2b05-47d3-95b6-6f3b445bb829",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41d0ad-98af-4012-85f4-2bfdbacca4d3",
        "name" => "Instalasi CSSD dan Binatu",
        "email" => "unit8174@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d48d-2b08-4491-85a3-6ae5c33ef425",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41d0ad-9930-468c-ab2a-0ed9e49122b9",
        "name" => "Instalasi Forensik, Medikolegal dan Pemulsaran Jenazah",
        "email" => "unit2968@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d48d-2b11-4920-8a6d-58efd30c46fd",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41d0ad-9934-4ee0-867d-e3ec80a8b8e2",
        "name" => "Instalasi Gas Medik",
        "email" => "unit6235@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d48d-2b14-419a-af63-27660177476d",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41d0ea-7611-4b38-85fb-8739c8bbee8b",
        "name" => "Instalasi Farmasi",
        "email" => "unit7601@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d48d-2b16-4e59-a4f9-bfd868a9e005",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41d0ea-768d-4fe9-a8d1-9cabd56e222d",
        "name" => "Instalasi Patologi Anatomi",
        "email" => "unit1122@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d48d-2b18-4c64-ba96-33df9e052614",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41d0ea-7691-4215-969b-d9cd5c021fde",
        "name" => "Sub Bidang Penunjang Pelayanan",
        "email" => "unit2459@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d48d-2b1a-41a5-ad70-814bcf041d6b",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41d12e-54d7-4ae4-bfed-0b1ef3695f38",
        "name" => "Instalasi Pemeliharaan Sarana dan Prasarana",
        "email" => "unit7005@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d55c-683e-417b-ae17-c70c079724bd",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41d12e-5555-4b03-a1cf-5662d045f190",
        "name" => "Instalasi Sanitasi",
        "email" => "unit4732@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d55c-68bc-481d-b8e5-9ee6166649f8",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41d12e-5558-4e1b-a556-a2499acdd6f7",
        "name" => "Sub Bidang Umum",
        "email" => "unit2017@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d55c-68bf-42b7-b6c9-c89aa3160d4c",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41d171-e567-42ac-b215-56223938a150",
        "name" => "Sub Bidang Sumber Daya Manusia",
        "email" => "unit6543@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d55c-68c2-47c8-a39f-c2ff02c54ec6",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41d171-e5e1-4c23-b3f1-d55770554e48",
        "name" => "Sub Bidang Keuangan",
        "email" => "unit3126@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d55c-68c4-430c-ac26-5ae84d250b98",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41d171-e5e4-41c5-8a33-c117670e46d5",
        "name" => "Sub Bidang Perencanaan dan Evaluasi",
        "email" => "unit2050@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d55c-68c6-458d-9907-fe44487b85a7",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41d1ab-9f2a-4825-a442-917e212de009",
        "name" => "Instalasi SIMRS",
        "email" => "unit1357@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d55c-68c8-4500-adcc-cd29c7c12d3e",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41d1ab-9fa4-4480-b372-6634f5fdaad9",
        "name" => "Sub Bidang Informasi dan Rekam Medis",
        "email" => "unit2065@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d55c-68ca-458f-a333-b1c20dd9a835",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "9d41d1ab-9fa7-46b9-a329-8ffc43e4ad7f",
        "name" => "Sub Bidang Diklat dan Litbang",
        "email" => "unit4764@admin.com",
        "role_id" => 5,
        "unit_id" => "9d41d55c-68cc-4d48-b394-286959911c95",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
    ];

    foreach ($user_unit as $unit) {
      $user = User::factory()->create($unit);
      $user->assignRole('unit');
    }

  }
}
