<?php

namespace Database\Seeders;

use App\Models\Bidang;
use App\Models\Unit;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
  public function run(): void
  {
    // ------------------------------ SEEDING NON UNIT USER ------------------------------ //

    User::factory()->create([
      'id' => '002b9b3e-2dc4-4d7b-b514-43b63d4ec742',
      'name' => 'Administrator',
      'email' => 'admin@admin.com',
      'password' => '$2y$12$y.5MaysrjgvzzBSWAafL1OCURe3JQqpx4Lc/lxnpUALYBqvHkQ3kq',
      'role_id' => 2,
    ])->assignRole('administrator');

    User::factory()->create([
      'id' => '03615fc8-956d-4493-9cfa-4a714b305560',
      'name' => 'Pimpinan',
      'email' => 'pimpinan@admin.com',
      'password' => '$2y$12$y.5MaysrjgvzzBSWAafL1OCURe3JQqpx4Lc/lxnpUALYBqvHkQ3kq',
      'role_id' => 3,
    ])->assignRole('pimpinan');

    User::factory()->create([
      'id' => '16f5d019-ec9c-4669-803b-fcfa3c2da686',
      'name' => 'Perencana',
      'email' => 'perencana@admin.com',
      'password' => '$2y$12$y.5MaysrjgvzzBSWAafL1OCURe3JQqpx4Lc/lxnpUALYBqvHkQ3kq',
      'role_id' => 4,
    ])->assignRole('perencana');

    // ------------------------------ SEEDING BIDANG USER ------------------------------ //

    Bidang::all()->each(function ($bidang) {
      User::factory()->create([
        'id' => Str::uuid(),
        'name' => $bidang->b_name,
        'email' => Str::slug($bidang->b_name, '') . '@admin.com',
        "password" => '$2y$12$y.5MaysrjgvzzBSWAafL1OCURe3JQqpx4Lc/lxnpUALYBqvHkQ3kq',
        'role_id' => 6,
        'bidang_id' => $bidang->id,
      ])->assignRole('bidang');
    });

    // ------------------------------ SEEDING UNIT USER ------------------------------ //

    // Unit::all()->each(function ($unit) {
    //   User::factory()->create([
    //     'id' => Str::uuid(),
    //     'name' => $unit->u_name,
    //     'email' => 'unit' . fake()->unique()->numberBetween($min = 1000, $max = 9000) . '@admin.com',
    //     "password" => "$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq",
    //     'role_id' => 5,
    //     'unit_id' => $unit->id,
    //   ]);
    // });

    // Seeds below are generated by code above //

    $user_unit = [
      [
        "id" => "011feb3a-9f94-489b-98c6-9a0728ebb23b",
        "name" => "Kelompok Staf Medis",
        "email" => "unit2213@admin.com",
        "role_id" => 5,
        "unit_id" => "f35cfb7d-52fe-4c52-90c4-2bc907987b09",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "0188b132-0e93-4d6b-bae0-7167b43a2d13",
        "name" => "Sub Bidang Pelayanan Medis",
        "email" => "unit8690@admin.com",
        "role_id" => 5,
        "unit_id" => "d7dd2920-37c2-4d5d-8d6b-d974f047806b",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "02a8b74c-55ed-4072-85b5-69ddc6d9c876",
        "name" => "Instalasi Rawat Inap",
        "email" => "unit6913@admin.com",
        "role_id" => 5,
        "unit_id" => "2fd31e71-9334-46e5-aae2-4a21ffefdf52",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "101c9d89-fc51-42a4-924e-d1adec00034b",
        "name" => "Instalasi Rawat Jalan",
        "email" => "unit7182@admin.com",
        "role_id" => 5,
        "unit_id" => "b433c233-b91f-4b41-ab33-b39f9433174e",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "18c3c85c-285e-4675-a863-216f4d9c384f",
        "name" => "Instalasi Kamar Bersalin",
        "email" => "unit8171@admin.com",
        "role_id" => 5,
        "unit_id" => "71d97120-0b57-485c-a827-36d51a73d03a",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "1b2ab3eb-b8df-4640-87e2-8fdb7be05fac",
        "name" => "Instalasi Bedah Sentral",
        "email" => "unit2623@admin.com",
        "role_id" => 5,
        "unit_id" => "4524d4c8-f794-4ac4-a714-41b09cec3ace",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "1bf69175-65fd-449c-bcb4-abb0d7d0aff3",
        "name" => "ICCU",
        "email" => "unit7393@admin.com",
        "role_id" => 5,
        "unit_id" => "c3e7722b-ac2a-475a-aaff-e60ec390cebb",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "1e84ab62-f3d8-49b6-9d3d-cc40ec79221a",
        "name" => "ICU",
        "email" => "unit1986@admin.com",
        "role_id" => 5,
        "unit_id" => "4360a591-c744-45d8-9618-16aa42a3382b",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "22ccc500-d9b5-4948-9d67-7e3cb6cff236",
        "name" => "NICU",
        "email" => "unit8834@admin.com",
        "role_id" => 5,
        "unit_id" => "b1c40f06-e7a7-4550-bfff-c5876319a6f7",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "230f69d6-baaa-4875-8768-612390b715b5",
        "name" => "PICU",
        "email" => "unit3858@admin.com",
        "role_id" => 5,
        "unit_id" => "97926780-f074-44be-ad8c-dde6abc79695",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "2356e6b0-0a92-4bac-ae4c-f72e5b0012b0",
        "name" => "Sub Bidang Pelayanan Keperawatan",
        "email" => "unit3079@admin.com",
        "role_id" => 5,
        "unit_id" => "78b574ad-bad8-47fa-81b2-bab72e355d48",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "23c51699-20ff-4ec3-a2ea-f9d9e196a8cf",
        "name" => "Instalasi Radiologi",
        "email" => "unit3865@admin.com",
        "role_id" => 5,
        "unit_id" => "68addb8c-86cc-462a-8f7b-a15eb24bf2fe",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "2517781d-d0a8-4905-b2ae-e36931d0584d",
        "name" => "Instalasi Gizi",
        "email" => "unit4117@admin.com",
        "role_id" => 5,
        "unit_id" => "95c5b442-e3fc-4821-9e6c-04d9f08cf2b8",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "2709616e-058a-4d07-bb8d-f1682ca6a84b",
        "name" => "Instalasi Patologi Klinik",
        "email" => "unit8516@admin.com",
        "role_id" => 5,
        "unit_id" => "411fb01e-a56b-47ff-82dd-f847a8adbdd0",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "2bdbcd18-b7f8-4720-96aa-4c67d18fb449",
        "name" => "Instalasi Rehabilitasi Medik",
        "email" => "unit7925@admin.com",
        "role_id" => 5,
        "unit_id" => "0b5e95f6-30d0-430d-b2de-e5826de6d96e",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "31cef58a-8080-40cf-8266-23e134b61b16",
        "name" => "Instalasi CSSD dan Binatu",
        "email" => "unit8174@admin.com",
        "role_id" => 5,
        "unit_id" => "de59808c-7ac5-4b80-8477-e7509f2db1f1",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "3f8591b7-ccf4-4e25-a865-79d4d12b8cdf",
        "name" => "Instalasi Forensik, Medikolegal dan Pemulsaran Jenazah",
        "email" => "unit2968@admin.com",
        "role_id" => 5,
        "unit_id" => "61c7a731-1c33-4fd7-88b2-e12506b9a075",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "400cdcfc-9937-455e-a80b-640c526484a4",
        "name" => "Instalasi Gas Medik",
        "email" => "unit6235@admin.com",
        "role_id" => 5,
        "unit_id" => "99b7c26f-9676-4a74-aa48-805fa9fefcd5",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "445211d3-9e62-4290-8854-b75884cce233",
        "name" => "Instalasi Farmasi",
        "email" => "unit7601@admin.com",
        "role_id" => 5,
        "unit_id" => "5a06b3e0-3036-45fd-b39b-15ace9a505fd",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "4531f62f-c16c-4272-8adf-e1dbf7abdf43",
        "name" => "Instalasi Patologi Anatomi",
        "email" => "unit1122@admin.com",
        "role_id" => 5,
        "unit_id" => "43b5901a-7d9a-4b93-b75b-9e3372918571",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "46def8a7-1b49-407e-9f21-82076aa2fc77",
        "name" => "Sub Bidang Penunjang Pelayanan",
        "email" => "unit2459@admin.com",
        "role_id" => 5,
        "unit_id" => "bf96b6c1-2725-455a-b908-ab82bee9236f",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "4b15cae0-3f06-4734-aba8-f4364bcc3c0c",
        "name" => "Instalasi Pemeliharaan Sarana dan Prasarana",
        "email" => "unit7005@admin.com",
        "role_id" => 5,
        "unit_id" => "97ab02b3-b062-40c6-9e87-a84077d7d5ab",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "4d3c9ee4-4f16-407c-a460-523f3ba05971",
        "name" => "Instalasi Sanitasi",
        "email" => "unit4732@admin.com",
        "role_id" => 5,
        "unit_id" => "aedfc9ef-5fce-4754-8360-24f2bbf30af0",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "5141813d-3cf0-4404-8407-837e99d40dee",
        "name" => "Sub Bidang Umum",
        "email" => "unit2017@admin.com",
        "role_id" => 5,
        "unit_id" => "9e86e663-7008-42f0-9955-d168380874cd",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "5d0cf6cb-267a-4a0b-b8ad-b583bddb5835",
        "name" => "Sub Bidang Sumber Daya Manusia",
        "email" => "unit6543@admin.com",
        "role_id" => 5,
        "unit_id" => "85d14bf2-2f99-47fc-ae11-d8a95cc1ada6",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "5dc88fde-9b2f-4800-944e-76486b0942ea",
        "name" => "Sub Bidang Keuangan",
        "email" => "unit3126@admin.com",
        "role_id" => 5,
        "unit_id" => "5cf4b10a-5064-4973-8efb-54ea2f57388f",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "60453ce8-aa01-43f7-9497-7dc624517d43",
        "name" => "Sub Bidang Perencanaan dan Evaluasi",
        "email" => "unit2050@admin.com",
        "role_id" => 5,
        "unit_id" => "89ee45c5-1245-419a-a2a0-cbda76ea6745",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "612baa58-d411-4c07-9fda-61028761ac5e",
        "name" => "Instalasi SIMRS",
        "email" => "unit1357@admin.com",
        "role_id" => 5,
        "unit_id" => "d130f8a9-dbc0-439e-9989-869411006a76",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "6384f45e-3a6f-4fc6-901b-fa1a449f36ef",
        "name" => "Sub Bidang Informasi dan Rekam Medis",
        "email" => "unit2065@admin.com",
        "role_id" => 5,
        "unit_id" => "9517cf6a-6d3b-465c-9437-8d89a8ce39bf",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
      [
        "id" => "6dd4d66f-769b-4f8a-8702-b96d73b6e07a",
        "name" => "Sub Bidang Diklat dan Litbang",
        "email" => "unit4764@admin.com",
        "role_id" => 5,
        "unit_id" => "c20fca05-487f-4ba0-a272-7e8e0231fa29",
        "password" => '$2y$12$TNq8.uhbKB9ZwUcak0k3puM9SWuD.di0nGMW0WzX0wnLcCtyv5Jlq',
      ],
    ];

    foreach ($user_unit as $unit) {
      $user = User::factory()->create($unit);
      $user->assignRole('unit');
    }

  }
}
